# See https://www.chirpstack.io/application-server/install/config/ for a full
# configuration example and documentation.

[postgresql]
dsn="postgres://loraserver_as:keti@localhost/loraserver_as?sslmode=disable"

[redis]
url="redis://localhost:6379"

[application_server.integration.mqtt]
server="tcp://127.0.0.1:1883"

[application_server.api]
#public_host="chirpstack-application-server:8001"
public_host="127.0.0.1:8001"

[application_server.external_api]
bind="0.0.0.0:8080"
jwt_secret="L5r1NwhnA6t9ewR9te58F8dFe2PxSQWytNtQw5zWzik="
#jwt_secret=""
